name: build container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build multi-arch images
  jobs-build-images:
    runs-on: [self-hosted, Linux, X64]
    timeout-minutes: 7200
    steps:
    - uses: actions/checkout@v2

    - name: Login to Quay.io Registry
      run: sudo docker login -u=${{ secrets.DOCKERHUB_USERNAME }} -p=${{ secrets.DOCKERHUB_PASSWORD }} quay.io

    - name: build multi-arch image
      timeout-minutes: 7200
      run: sudo ./build_container/docker_build.sh `date +'%Y-%m-%d'`

  # build arm64 images
  jobs-arm64:
    continue-on-error: true
    runs-on: [self-hosted, Linux, ARM64]
    timeout-minutes: 7200
    steps:
    - uses: actions/checkout@v2

    - name: Login to Quay.io Registry
      run: sudo  docker login -u=${{ secrets.DOCKERHUB_USERNAME }} -p=${{ secrets.DOCKERHUB_PASSWORD }} quay.io

    - name: build arm64 image
      timeout-minutes: 7200
      run: sudo ./build_container/docker_build.sh `date +'%Y-%m-%d'`
